spring.application.name=leave_manager
# Server
server.port=8080

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/leave_database?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=mysql@MaHa20
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=leavesync_super_secret_key_2024_hackathon_secure_long_enough
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# Logging
logging.level.com.leavesync=DEBUG
logging.level.org.springframework.security=DEBUG